### ISSUE TITLE
Some blog posts are broken

### ISSUE THREAD

**Issue by cpojer** [spences10/scottspence.com#483]
Hi Scott!

I went to https://scottspence.com/posts and typed "mdx" to get to this post: https://github.com/spences10/scottspence.com/blob/main/posts/2021/02/16/making-mdx-presentations/index.md

It shows up, but when I click it it takes me to a 404 page: https://scottspence.com/posts/making-mdx-presentations

This also appears to be happening for some other old posts.

Just figured you'll want to know!

**Comment by spences10** [comment]
Hey @cpojer thank you for letting me know, I had a similar experience the other day as well

I'm now going to have a root through all the posts now, definitely something to do with the page analytics I added at the start of the week

**Comment by spences10** [comment]
Look like I missed an optional parameter!

This is why test are important, right Chris 😄

**Comment by spences10** [comment]
Ok, this also helped me fix the routing issue that cropped up from the SvelteKit v1 release which I YOLO patched back in August and have now implemented a proper fix for it.

Thanks Chris, closing this now.

**Comment by spences10** [comment]
Fixed with c4b3a53a683d70db8282ff11aa3f7adc364b8e8b and feb932e8c818d6a9276badb4895602473c914fd6
